# Generated by: op inject -i apps/admin-web/.env.op.tpl -o apps/admin-web/.env.local
NEXT_PUBLIC_API_URL=http://localhost:3000
NEXTAUTH_SECRET={{ op://Cleanly/JWT Secrets/nextauth_secret }}
NEXTAUTH_URL=http://localhost:3003
GOOGLE_CLIENT_ID={{ op://Cleanly/Google OAuth/client_id }}
GOOGLE_CLIENT_SECRET={{ op://Cleanly/Google OAuth/client_secret }}
ADMIN_EXCHANGE_SECRET={{ op://Cleanly/JWT Secrets/admin_exchange_secret }}
NEXT_PUBLIC_SENTRY_DSN={{ op://Cleanly/Sentry/admin_web_dsn }}
