# Generated by: op inject -i apps/customer-mobile/.env.op.tpl -o apps/customer-mobile/.env
EXPO_PUBLIC_API_URL=http://localhost:3000
EXPO_PUBLIC_PROJECT_ID={{ op://Cleanly/Expo EAS/customer_project_id }}
EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY={{ op://Cleanly/Stripe/publishable_key_test }}
EXPO_PUBLIC_SENTRY_DSN={{ op://Cleanly/Sentry/customer_mobile_dsn }}
