# Generated by: op inject -i apps/washer-mobile/.env.op.tpl -o apps/washer-mobile/.env
EXPO_PUBLIC_API_URL=http://localhost:3000
EXPO_PUBLIC_PROJECT_ID={{ op://Cleanly/Expo EAS/washer_project_id }}
EXPO_PUBLIC_GOOGLE_MAPS_API_KEY={{ op://Cleanly/Google Maps/api_key }}
EXPO_PUBLIC_SENTRY_DSN={{ op://Cleanly/Sentry/washer_mobile_dsn }}
