# Generated by: op inject -i apps/customer-web/.env.op.tpl -o apps/customer-web/.env.local
NEXT_PUBLIC_API_URL=http://localhost:3000
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY={{ op://Cleanly/Stripe/publishable_key_test }}
NEXT_PUBLIC_SENTRY_DSN={{ op://Cleanly/Sentry/customer_web_dsn }}
