# Generated by: op inject -i apps/api/.env.op.tpl -o apps/api/.env
# Requires: 1Password CLI installed + authenticated + access to "Cleanly" vault

NODE_ENV=development
PORT=3000
HOST=0.0.0.0
LOG_LEVEL=info

DATABASE_URL={{ op://Cleanly/Neon Production/database_url_pooled }}
DIRECT_URL={{ op://Cleanly/Neon Production/direct_url }}

UPSTASH_REDIS_URL={{ op://Cleanly/Upstash Redis/connection_string }}
UPSTASH_REDIS_REST_URL={{ op://Cleanly/Upstash Redis/rest_url }}
UPSTASH_REDIS_REST_TOKEN={{ op://Cleanly/Upstash Redis/rest_token }}

JWT_SECRET={{ op://Cleanly/JWT Secrets/jwt_secret }}
JWT_REFRESH_SECRET={{ op://Cleanly/JWT Secrets/jwt_refresh_secret }}

TWILIO_ACCOUNT_SID={{ op://Cleanly/Twilio/account_sid }}
TWILIO_AUTH_TOKEN={{ op://Cleanly/Twilio/auth_token }}
TWILIO_VERIFY_SERVICE_SID={{ op://Cleanly/Twilio/verify_service_sid }}

STRIPE_SECRET_KEY={{ op://Cleanly/Stripe/secret_key_test }}

RESEND_API_KEY={{ op://Cleanly/Resend/api_key }}

DIALOG360_API_KEY={{ op://Cleanly/360dialog/api_key }}

R2_ACCOUNT_ID={{ op://Cleanly/Cloudflare R2/account_id }}
R2_ACCESS_KEY_ID={{ op://Cleanly/Cloudflare R2/access_key_id }}
R2_SECRET_ACCESS_KEY={{ op://Cleanly/Cloudflare R2/secret_access_key }}
R2_BUCKET_NAME=cleanly-photos
R2_PUBLIC_URL={{ op://Cleanly/Cloudflare R2/public_url }}

SENTRY_DSN={{ op://Cleanly/Sentry/api_dsn }}
SENTRY_ORG=cleanly

ADMIN_EXCHANGE_SECRET={{ op://Cleanly/JWT Secrets/admin_exchange_secret }}

CUSTOMER_WEB_URL=http://localhost:3001
COMPANY_WEB_URL=http://localhost:3002
ADMIN_WEB_URL=http://localhost:3003
CUSTOMER_MOBILE_URL=http://localhost:8081
WASHER_MOBILE_URL=http://localhost:8082

WHATSAPP_ENABLED=false
BYPASS_SENTRY=false
